(setq modes-list
      '(("\\.\\(md\\|markdown\\)$" . markdown-mode)
        ("\\.twig$" . jinja2-mode)
        ("PKGBUILD" . sh-mode)
        ("\\.yml$" . yaml-mode)
        ("\\.rst$" . rst-mode)
        ("\\.lua$" . lua-mode)
        ("\\.htaccess$" . apache-mode)
        ("httpd.*\\.conf$" . apache-mode)
        ("srm\\.conf$" . apache-mode)
        ("access\\.conf$" . apache-mode)
        ("\\.rake$" . ruby-mode)
        ("Rakefile" . ruby-mode)
        ("Gemfile" . ruby-mode)
        ("Guardfile" . ruby-mode)
        ("\\.erb$" . rhtml-mode)
        ("\\.feature$" . feature-mode)
        ("\\.scss$" . sass-mode)
        ("\\.tpl$" . html-mode)
        ("\\.scala$" . scala-mode)
        ("sites-\\(available\\|enabled\\)/" . apache-mode)))

(dolist (alist modes-list)
  (add-to-list 'auto-mode-alist alist))

(provide 'default-auto-modes)
;;; default-auto-modes.el ends here
