(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector [solarized-bg red green yellow blue magenta cyan solarized-fg])
 '(c-label-minimum-indentation 2)
 '(c-syntactic-indentation t)
 '(custom-safe-themes (quote ("be7eadb2971d1057396c20e2eebaa08ec4bfd1efe9382c12917c6fe24352b7c1" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "27b53b2085c977a8919f25a3a76e013ef443362d887d52eaa7121e6f92434972" "6d574efe12e7f595e5e1cf036ce2c0a4e9fcb96c01270c3851c688470bd6cf97" "a4d62b12bfa8be9ec8e66f257d244d6c18b61c84bcb2b8cb10beff7ae8bd744a" "3e9abefc0d6deea78925ccd71c1943b74ab0f487592cb2ff55c612dd7f8cd0e5" "08182dd3d78728e88a5262ac15b2681cd0110153839d2a92577bfc55e06df91d" "813497619e5ed02d10aa16b237c74fa6d440126d9b3a1c1ff4329ac7f2c3a3e7" "baed08a10ff9393ce578c3ea3e8fd4f8c86e595463a882c55f3bd617df7e5a45" "284aece21e57abcf7c7d5f273d2d17dc646b24cb1465fd054ad9dca3555aed1c" "54d1bcf3fcf758af4812f98eb53b5d767f897442753e1aa468cfeb221f8734f9" "b7553781f4a831d5af6545f7a5967eb002c8daeee688c5cbf33bf27936ec18b3" "9d2a85a8574b72d2dbbe643102209e0c0edbb6e8" default)))
 '(espresso-auto-indent-flag nil)
 '(espresso-expr-indent-offset 0)
 '(espresso-indent-level 4 t)
 '(fci-rule-color "#073642")
 '(flyspell-duplicate-distance -1)
 '(gnus-agent-enable-expiration (quote ENABLE))
 '(gnus-agent-expire-days 30)
 '(gnus-always-force-window-configuration nil)
 '(gnus-always-read-dribble-file t)
 '(gnus-article-date-headers (quote (combined-lapsed)))
 '(gnus-article-skip-boring t)
 '(gnus-article-sort-functions (quote (gnus-article-sort-by-number gnus-article-sort-by-score)))
 '(gnus-asynchronous nil)
 '(gnus-auto-goto-ignores (quote undownloaded))
 '(gnus-auto-select-next nil)
 '(gnus-boring-article-headers (quote (empty)))
 '(gnus-build-sparse-threads (quote some))
 '(gnus-demon-handlers (quote ((gnus-group-get-new-news 30 30))))
 '(gnus-fetch-old-ephemeral-headers (quote some))
 '(gnus-fetch-old-headers (quote some))
 '(gnus-inhibit-images nil)
 '(gnus-interactive-exit (quote quiet))
 '(gnus-keep-backlog 100)
 '(gnus-mode-non-string-length nil)
 '(gnus-posting-styles (quote ((".*" (name "Jeremiah Dodds") (address "https://github.com/jdodds")))))
 '(gnus-read-newsrc-file nil)
 '(gnus-save-duplicate-list t)
 '(gnus-save-killed-list nil)
 '(gnus-save-newsrc-file nil)
 '(gnus-show-all-headers nil)
 '(gnus-summary-ignore-duplicates t)
 '(gnus-summary-stop-at-end-of-message t)
 '(gnus-suppress-duplicates t)
 '(gnus-thread-hide-subtree nil)
 '(gnus-thread-sort-functions (quote (gnus-thread-sort-by-number gnus-thread-sort-by-total-score)))
 '(gnus-treat-from-gravatar (quote head))
 '(gnus-treat-mail-gravatar (quote head))
 '(gnus-use-adaptive-scoring (quote (word)))
 '(gnus-use-correct-string-widths t)
 '(gnus-use-trees nil)
 '(gnus-user-agent (quote (gnus emacs type)))
 '(gnus-verbose 5)
 '(gnus-verbose-backends 5)
 '(gnus-view-pseudos (quote automatic))
 '(markdown-command "markdown")
 '(markdown-italic-underscore t)
 '(mm-inline-large-images (quote resize))
 '(mm-inline-text-html-with-images t)
 '(mm-url-arguments nil)
 '(mm-url-program (quote curl))
 '(org-agenda-files (quote ("~/workspace/planning/eric.fawcett.org" "~/workspace/iquotex/TODO.org" "~/workspace/planning/leadsvend.org" "~/workspace/cl-lead-scraper/TODO.org" "~/workspace/nvd3charts/TODO.org" "~/workspace/mundo-media/TODO.org" "~/workspace/leadwerks/TODO.org" "~/workspace/youtube-vid-creator/TODO.org" "~/workspace/planning/refile.org" "~/workspace/planning/projects.org" "~/workspace/planning/software.org" "~/workspace/planning/personal.org" "~/workspace/planning/learning.org" "~/workspace/planning/music.org" "~/workspace/planning/TODO.org")))
 '(php+-mode-delete-trailing-whitespace t)
 '(php+-mode-php-compile-on-save t)
 '(php+-mode-show-project-in-modeline t)
 '(php-blank-line-at-end-of-class nil)
 '(php-executable "/usr/bin/php")
 '(php-html-basic-offset 4)
 '(php-manual-path "/usr/share/doc/php/php-chunked-xhtml/")
 '(php-project-list (quote (("leadsven" "/home/jdd/workspace/leadsven" "/home/jdd/workspace/leadsven/TAGS" nil "/home/jdd/workspace/leadsven/phpunit.xml.cli.dist" ("/home/jdd/workspace/leadsven/src") (("" . "") "" "" "" "" "" "" "" "") "" ""))))
 '(php-tag-ignore-patterns (quote (".svn" ".git")))
 '(php-test-compile-tests (quote (lint phpcs phpmd)))
 '(php-test-show-command nil)
 '(phpcs-standard "Leadsven")
 '(python-honour-comment-indentation nil)
 '(python-skeleton-autoinsert nil)
 '(python-use-skeletons nil)
 '(qooxdoo-compile-on-save nil)
 '(rcirc-buffer-maximum-lines 500)
 '(rcirc-default-nick "exhortatory")
 '(rcirc-log-flag t)
 '(ruby-deep-arglist nil)
 '(ruby-deep-indent-paren nil)
 '(shr-color-visible-distance-min 10)
 '(shr-color-visible-luminance-min 60)
 '(sql-database "")
 '(sql-mysql-program "/usr/bin/mysql")
 '(sql-server "localhost")
 '(startproject-projects-root "~/workspace")
 '(tag-shell-command "/usr/bin/ctags")
 '(term-bind-key-alist (quote (("C-c C-c" . term-interrupt-subjob) ("C-p" . previous-line) ("C-n" . next-line) ("C-s" . isearch-forward) ("C-r" . isearch-backward) ("C-m" . term-send-raw) ("M-f" . term-send-forward-word) ("M-b" . term-send-backward-word) ("M-o" . term-send-backspace) ("M-p" . term-send-up) ("M-n" . term-send-down) ("M-M" . term-send-forward-kill-word) ("M-N" . term-send-backward-kill-word) ("M-r" . term-send-reverse-search-history) ("M-," . term-send-input) ("M-." . comint-dynamic-complete) ("C-a" . term-bol))))
 '(term-unbind-key-list (quote ("C-z" "C-x" "C-c" "C-h" "C-y" "<ESC>" "C-k" "C-e")))
 '(trelloel-oauth-token (read-from-minibuffer "Token: "))
 '(trelloel-username "jeremiahdodds")
 '(user-full-name "Jeremiah Dodds")
 '(w3-honor-stylesheets t)
 '(w3-reuse-buffers (quote no))
 '(w3-use-unicode-table-characters t)
 '(wtf-custom-alist (quote (("EIP" . "Extended Instruction Pointer")))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#000000" :foreground "#F6F3E8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 80 :width normal :foundry "bitstream" :family "Meslo LG S DZ"))))
 '(compilation-error ((t (:inherit nil :foreground "red" :weight bold))))
 '(dired-directory ((t (:inherit font-lock-function-name-face :background "dim gray" :box (:line-width 2 :color "dim gray" :style released-button)))))
 '(gnus-summary-selected ((t (:underline t :weight bold))) t)
 '(highlight-80+ ((t (:background "red"))) t)
 '(magit-branch ((t (:inherit magit-header :foreground "deep sky blue")))))
