(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector [solarized-bg red green yellow blue magenta cyan solarized-fg])
 '(c-label-minimum-indentation 2)
 '(c-syntactic-indentation t)
 '(custom-safe-themes (quote ("6d574efe12e7f595e5e1cf036ce2c0a4e9fcb96c01270c3851c688470bd6cf97" "a4d62b12bfa8be9ec8e66f257d244d6c18b61c84bcb2b8cb10beff7ae8bd744a" "3e9abefc0d6deea78925ccd71c1943b74ab0f487592cb2ff55c612dd7f8cd0e5" "08182dd3d78728e88a5262ac15b2681cd0110153839d2a92577bfc55e06df91d" "813497619e5ed02d10aa16b237c74fa6d440126d9b3a1c1ff4329ac7f2c3a3e7" "baed08a10ff9393ce578c3ea3e8fd4f8c86e595463a882c55f3bd617df7e5a45" "284aece21e57abcf7c7d5f273d2d17dc646b24cb1465fd054ad9dca3555aed1c" "54d1bcf3fcf758af4812f98eb53b5d767f897442753e1aa468cfeb221f8734f9" "b7553781f4a831d5af6545f7a5967eb002c8daeee688c5cbf33bf27936ec18b3" "9d2a85a8574b72d2dbbe643102209e0c0edbb6e8" default)))
 '(espresso-auto-indent-flag nil)
 '(espresso-expr-indent-offset 0)
 '(espresso-indent-level 4 t)
 '(fci-rule-color "#073642")
 '(flyspell-duplicate-distance -1)
 '(gnus-agent-enable-expiration (quote ENABLE))
 '(gnus-agent-expire-days 30)
 '(gnus-always-force-window-configuration nil)
 '(gnus-always-read-dribble-file t)
 '(gnus-article-date-headers (quote (combined-lapsed)))
 '(gnus-article-skip-boring t)
 '(gnus-article-sort-functions (quote (gnus-article-sort-by-number gnus-article-sort-by-score)))
 '(gnus-asynchronous nil)
 '(gnus-auto-goto-ignores (quote undownloaded))
 '(gnus-auto-select-next nil)
 '(gnus-boring-article-headers (quote (empty)))
 '(gnus-build-sparse-threads (quote some))
 '(gnus-demon-handlers (quote ((gnus-group-get-new-news 30 30))))
 '(gnus-fetch-old-ephemeral-headers (quote some))
 '(gnus-fetch-old-headers (quote some))
 '(gnus-inhibit-images nil)
 '(gnus-interactive-exit (quote quiet))
 '(gnus-keep-backlog 100)
 '(gnus-mode-non-string-length nil)
 '(gnus-posting-styles (quote ((".*" (name "Jeremiah Dodds") (address "https://github.com/jdodds")))))
 '(gnus-read-newsrc-file nil)
 '(gnus-save-duplicate-list t)
 '(gnus-save-killed-list nil)
 '(gnus-save-newsrc-file nil)
 '(gnus-show-all-headers nil)
 '(gnus-summary-ignore-duplicates t)
 '(gnus-summary-stop-at-end-of-message t)
 '(gnus-suppress-duplicates t)
 '(gnus-thread-hide-subtree nil)
 '(gnus-thread-sort-functions (quote (gnus-thread-sort-by-number gnus-thread-sort-by-total-score)))
 '(gnus-treat-from-gravatar (quote head))
 '(gnus-treat-mail-gravatar (quote head))
 '(gnus-use-adaptive-scoring (quote (word)))
 '(gnus-use-correct-string-widths t)
 '(gnus-use-trees nil)
 '(gnus-user-agent (quote (gnus emacs type)))
 '(gnus-verbose 5)
 '(gnus-verbose-backends 5)
 '(gnus-view-pseudos (quote automatic))
 '(markdown-command "markdown")
 '(markdown-italic-underscore t)
 '(mm-inline-large-images (quote resize))
 '(mm-inline-text-html-with-images t)
 '(mm-url-arguments nil)
 '(mm-url-program (quote curl))
 '(org-agenda-files (quote ("~/Dropbox/projects.org" "~/workspace/idatasystems/quotes/TODO.org" "~/Dropbox/software.org" "~/Dropbox/personal.org" "~/Dropbox/learning.org" "~/Dropbox/music.org" "~/Dropbox/MobileOrg/flagged.org" "~/Dropbox/shopping.org" "~/Dropbox/TODO.org" "~/Dropbox/immediate.org")))
 '(org-edit-src-content-indentation 0)
 '(org-src-window-setup (quote other-frame))
 '(org-startup-with-inline-images t)
 '(php-executable "~/bin/php")
 '(python-honour-comment-indentation nil)
 '(python-use-skeletons nil)
 '(qooxdoo-compile-on-save nil)
 '(rcirc-default-nick "exhortatory")
 '(rcirc-log-flag t)
 '(ruby-deep-arglist nil)
 '(ruby-deep-indent-paren nil)
 '(safe-local-variable-values (quote ((tab-width 4) (indent-tabs-mode t) (sgml-basic-offset . 3) (js-indent-level . 3))))
 '(sh-basic-offset 2)
 '(shr-color-visible-distance-min 10)
 '(shr-color-visible-luminance-min 60)
 '(sql-database "")
 '(sql-mysql-program "/usr/bin/mysql")
 '(sql-server "localhost")
 '(startproject-projects-root "~/workspace")
 '(user-full-name "Jeremiah Dodds")
 '(w3-honor-stylesheets t)
 '(w3-reuse-buffers (quote no))
 '(w3-use-unicode-table-characters t)
 '(wtf-custom-alist (quote (("EIP" . "Extended Instruction Pointer")))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:height 90 :family "Inconsolata"))))
 '(dired-directory ((t (:inherit font-lock-function-name-face :background "dim gray" :box (:line-width 2 :color "dim gray" :style released-button)))))
 '(gnus-summary-selected ((t (:underline t :weight bold))))
 '(highlight-80+ ((t (:background "red"))) t))
