(setq modes-list
      '(("\\.md" . markdown-mode)
        ("\\.twig$" . django-html-mode)
        ("PKGBUILD" . sh-mode)
        ("\\.yml$" . yaml-mode)
        ("\\.rst$" . rst-mode)
        ("\\.org$" . org-mode)
        ("\\.php$" . php-mode)
        ("\\.lua$" . lua-mode)
        ("\\.htaccess$" . apache-mode)
        ("httpd.*\\.conf$" . apache-mode)
        ("srm\\.conf$" . apache-mode)
        ("access\\.conf$" . apache-mode)
        ("\\.rake$" . ruby-mode)
        ("Rakefile" . ruby-mode)
        ("Gemfile" . ruby-mode)
        ("\\.erb$" . rhtml-mode)
        ("\\.feature$" . feature-mode)
        ("sites-\\(available\\|enabled\\)/" . apache-mode)))
;(add-to-list 'auto-mode-alist '("\\.erb$" . rhtml-mode))
(dolist (alist modes-list)
  (add-to-list 'auto-mode-alist alist))

(provide 'default-auto-modes)
;;; default-auto-modes.el ends here
