(deftheme ir-black
  "Created 2012-10-10.")

(custom-theme-set-faces
 'ir-black
 '(bold ((t (:bold t))))
 '(button ((t (:foreground "#96CBFE" :underline t))))
 '(escape-glyph ((t (:foreground "#00A0A0"))))
 '(header-line ((t (:background "#202020" :foreground "#F6F3E8"))))
 '(highlight ((t (:background "#151515"))))
 '(highlight-face ((t (:background "#151515"))))
 '(hl-line ((t (:background "#151515" :underline t))))
 '(info-xref ((t (:foreground "#96CBFE" :underline t))))
 '(region ((t (:background "#262D51"))))
 '(underline ((nil (:underline t))))
 '(font-lock-builtin-face ((t (:foreground "#FFFFB6"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7C7C7C"))))
 '(font-lock-comment-face ((t (:foreground "#7C7C7C"))))
 '(font-lock-constant-face ((t (:foreground "#99CC99"))))
 '(font-lock-doc-face ((t (:foreground "#A8FF60"))))
 '(font-lock-doc-string-face ((t (:foreground "#A8FF60"))))
 '(font-lock-function-name-face ((t (:foreground "#FFD2A7"))))
 '(font-lock-keyword-face ((t (:foreground "#96CBFE"))))
 '(font-lock-negation-char-face ((t (:foreground "#FF6C60"))))
 '(font-lock-number-face ((t (:foreground "#FF73FD"))))
 '(font-lock-preprocessor-face ((t (:foreground "#96CBFE"))))
 '(font-lock-reference-face ((t (:foreground "#99CC99"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#E9C"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#E9C"))))
 '(font-lock-string-face ((t (:foreground "#A8FF60"))))
 '(font-lock-type-face ((t (:foreground "#FFFFB6"))))
 '(font-lock-variable-name-face ((t (:foreground "#C6C5FE"))))
 '(font-lock-warning-face ((t (:foreground "#FF6C60"))))
 '(fringe ((t (:background "#000000"))))
 '(linum ((t (:background "#3D3D3D"))))
 '(minibuffer-prompt ((t (:foreground "#C6C5FE"))))
 '(mode-line ((t (:background "#202020" :foreground "#CCCCCC"))))
 '(mode-line-inactive ((t (:background "#202020" :foreground "#000000"))))
 '(cursor ((t (:background "gray"))))
 '(text-cursor ((t (:background "gray"))))
 '(vertical-border ((t (:foreground "snow1"))))
 '(show-paren-mismatch ((t (:background "#FF6C60" :foreground "#F6F3E8" :weight bold))))
 '(show-paren-match ((t (:background "#96CBFE" :foreground "#F6F3E8" :weight bold))))
 '(isearch ((t (:background "#FF0" :foreground "#2F2F00"))))
 '(isearch-fail ((t (:background "#FF6C60"))))
 '(lazy-highlight ((t (:background "#FFFFB6" :foreground "#2F2F00"))))
 '(magit-diff-add ((t (:foreground "#A8FF60"))))
 '(magit-diff-del ((t (:foreground "#FF6C60"))))
 '(org-date ((t (:foreground "#FFCCFF" :underline t))))
 '(org-level-1 ((t (:foreground "#A8FF60"))))
 '(org-special-keyword ((t (:foreground "#C6C5FE"))))
 '(org-link ((t (:foreground "#96CBFE" :underline t))))
 '(org-checkbox ((t (:foreground "#96CBFE" :background "#000000" :bold t))))
 '(org-clock-overlay ((t (:foreground "#202020" :background "#A8FF60"))))
 '(esk-paren-face ((t (:foreground "#00A0A0"))))
 '(default ((t (:background "#000000" :foreground "#F6F3E8")))))

(provide-theme 'ir-black)
