;;; TODO :: Refactor these out into autoloads if possible.
;(require 'magit)
(require 'psvn)
(require 'qooxdoo)
;(require 'django-mode)
;(require 'django-html-mode)
(require 'auto-complete)
(require 'yaml-mode)
(require 'tramp)
(require 'rst)
;(require 'zenburn-theme)
;(require 'zencoding-mode)
(require 'color-theme)
(require 'uniquify)
(require 'rhtml-mode)
(require 'rinari)
(require 'haml-mode)
(require 'sass-mode)
(require 'which-func)
(require 'flymake)
(require 'flymake-cursor)
(require 'yasnippet)
;;; requires.el ends here
